- name: Install logrotate
  become: true
  apt:
    pkg:
      - logrotate

- name: Copy package to host.
  become: true
  copy:
    src: files/logrotate.conf
    dest: /etc/logrotate.conf
    owner: root
    group: root
    mode: '0644'
