# Configures a gapid/AGI test machine with everything it needs to run under switchboard.
- hosts: gapid_test_machines
  user: chrome-bot
  gather_facts: true

  roles:
    - copy_authorized_keys
    - copy_service_account_key
    - install_collectd
    - swarming_needs
    - switchboard_needs
    - install_test_machine_monitor
