# Configures a jumphost with everything it needs.
- hosts: jumphosts
  user: chrome-bot
  gather_facts: true
  vars:
    router_backup_ansible_version_override: ''
    powercycle_server_ansible_version_override: ''
    metadata_server_ansible_version_override: ''
    alert_to_pubsub_ansible_version_override: ''
    managed_prometheus_ansible_version_override: ''

  roles:
    - stop_sleeping
    - create_chrome_bot_user
    - copy_authorized_keys
    - copy_service_account_key
    - install_collectd
    - jumphost-lighttpd
    - role: install_metadata_server
      metadata_server_ansible_version:
        '{{ metadata_server_ansible_version_override }}'
    - role: install_powercycle_server
      powercycle_server_ansible_version:
        '{{ powercycle_server_ansible_version_override }}'
    - role: install_router_backup
      router_backup_ansible_version:
        '{{ router_backup_ansible_version_override }}'
    - role: install_alert_to_pubsub
      alert_to_pubsub_ansible_version:
        '{{ alert_to_pubsub_ansible_version_override }}'
    - role: install_managed_prometheus
      managed_prometheus_ansible_version:
        '{{ managed_prometheus_ansible_version_override }}'
