# Configures a Linux test machine with everything it needs to run under switchboard.
- hosts: all_linux
  user: chrome-bot
  gather_facts: true

  roles:
    - stop_sleeping
    - create_chrome_bot_user
    - copy_authorized_keys
    - copy_service_account_key
    - install_collectd
    - swarming_needs
    - switchboard_needs
    - install_test_machine_monitor
    - rfkill
    - logrotate
