# Does the absolute minimum for an RPI with an SD card that's been configured
# via //infra/skolo/rasperry-pi/switchboard/configure-image.sh
#
# Once this is run then the 'rpi.yml' playbook can be run to finish/update the
# machine.
- hosts: all_linux
  become: true
  gather_facts: false

  pre_tasks:
    # First install python3 so we can do more than issue 'raw' commands.
    - name: install python3
      raw:
        'apt update && apt -y install sudo python3 python3-apt python3-distutils'
