- name: Copy empty .boto file.
  copy:
    src: files/.boto
    dest: ~chrome-bot/.boto
    owner: 'chrome-bot'
    group: '{{ skolo_group }}'
    mode: 0644

- name: Create /etc/swarming_config directory
  become: true
  file:
    path: /etc/swarming_config
    state: directory
    recurse: true
    owner: '{{ skolo_account }}'
    mode: 0755

- name: Copy oauth2 config file
  become: true
  template:
    src: templates/oauth2_access_token_config.json
    dest: /etc/swarming_config/oauth2_access_token_config.json
    owner: '{{ skolo_account }}'
    mode: 0644
