- name: Mask all sleep services.
  become: true
  ansible.builtin.systemd:
    name: sleep.target
    masked: true

- name: Mask all sleep services.
  become: true
  ansible.builtin.systemd:
    name: suspend.target
    masked: true

- name: Mask all sleep services.
  become: true
  ansible.builtin.systemd:
    name: hibernate.target
    masked: true

- name: Mask all sleep services.
  become: true
  ansible.builtin.systemd:
    name: hybrid-sleep.target
    masked: true
