- name: Copy authorized_keys to Linux or Mac.
  import_tasks: posix.yml
  when: ansible_facts['system']|lower in ['darwin', 'linux']

- name: Copy authorized_keys to Win.
  import_tasks: win.yml
  when: ansible_facts['system']|lower == 'win32nt'
