# Requires Ansible 2.4 or newer
# Do all the things to set up a Skolo bot.
# Machine settings.
- import_playbook: skolo-settings.yml
# Prep for Swarming.
- import_playbook: ../../common/ansible/skolo-credentials.yml
# Start Swarming. Must be last, since the bot will start running tasks after this.
- import_playbook: ../../common/ansible/bootstrap-swarming.yml
