# Add .boto, and oauth2_access_token_config.json files to a Skolo bot.
- hosts: all
  tasks:
  # .boto doesn't need to contain anything, just needs to be present.
  - name: Create boto in home
    file:
      path: "{{ home }}/.boto"
      state: touch
  - name: Copy oauth2_access_token_config.json to swarming_config
    become: yes
    copy:
      src: ../../common/oauth2_access_token_config.json
      dest: /etc/swarming_config/
