- name: Fail if platform unsupported.
  fail:
    msg: This role is Windows-only.
  when: ansible_facts['system']|lower not in ['win32nt']

- name: Build getgpu.exe
  delegate_to: 127.0.0.1
  run_once: true
  command:
    argv:
      - bazelisk
      - build
      - --platforms=@io_bazel_rules_go//go/toolchain:windows_amd64
      - //skolo/go/getgpu

- name: Create Temp
  win_file:
    path: C:\Temp
    state: directory

- name: Copy getgpu.exe to host
  win_copy:
    src: '{{ all.repo_root }}/_bazel_bin/skolo/go/getgpu/getgpu_/getgpu.exe'
    dest: C:\Temp\getgpu.exe

- name: Run getgpu.exe
  win_command: C:\Temp\getgpu.exe
  register: getgpu

- name: Print out GPU
  debug:
    msg: 'Detected GPU: {{ getgpu.stdout }}'

- name: Install Nvidia driver
  import_tasks: nvidia.yml
  when: getgpu.stdout is match(".*Nvidia.*")

- name: Install Radeon driver
  import_tasks: radeon.yml
  when: getgpu.stdout is match(".*Radeon.*")

- name: Install Skylake driver
  import_tasks: skylake.yml
  when: getgpu.stdout is match(".*Skylake.*")

- name: Install Broadwell driver
  import_tasks: broadwell.yml
  when: getgpu.stdout is match(".*Broadwell.*")

- name: Install Iris Xe driver
  import_tasks: irisxe.yml
  when: getgpu.stdout is match(".*Iris\(R\) Xe.*")

- name: Cleanup getgpu.exe
  win_file:
    path: C:\Temp\getgpu.exe
    state: absent
