- name: Fail if platform unsupported.
  fail:
    msg: Cannot install Graphics Tools on platforms other than Windows.
  when: ansible_facts['system']|lower not in ['win32nt']

# Reference links:
# - https://docs.microsoft.com/en-us/visualstudio/debugger/graphics/getting-started-with-visual-studio-graphics-diagnostics
# - https://superuser.com/questions/1614143/how-to-enable-the-new-optional-features-using-powershell
- name: Install Graphics Tools for Windows 10.
  win_command: powershell.exe -
  args:
    stdin: Add-WindowsCapability -Online -Name Tools.Graphics.DirectX~~~~0.0.1.0
  # Prevents error "Access is denied".
  become: true
  become_user: chrome-bot
  # Prevents error "The powershell shell family is incompatible with the sudo become plugin".
  become_method: runas
